### ISSUE TITLE
is this video about  your ipinyou-data?

### ISSUE THREAD

**Issue by Sandy4321** [Atomu2014/Ads-RecSys-Datasets#10]
is this video about  your ipinyou-data?

Optimal Real-Time Bidding for Display Advertising
https://www.youtube.com/watch?v=OoI2aCWdWKA&t=2405s

**Comment by Atomu2014** [comment]
I think it's ipinyou-data, but you should notice CTR estimation and RTB are different tasks.
Thus I and the video authors are using different parts of the original complete logs.
