### ISSUE TITLE
有人维护吗

### ISSUE THREAD

**Issue by yufengwhy** [Atomu2014/Ads-RecSys-Datasets#3]
http://cloud.apexlab.org/s/caxY252qFxAIxe4
sudo mount -t nfs 172.16.2.30:/mnt/NAS/Dataset/Ads-RecSys-Datasets /your/local/path

这些链接都无法使用了？请问什么时候能使用？

**Comment by Atomu2014** [comment]
数据上传好之后，我会尽快更新下载链接

**Comment by yufengwhy** [comment]
谢谢，大概要多久？

**Comment by yufengwhy** [comment]
能不能把criteo数据集百度云共享一下？

**Comment by Atomu2014** [comment]
https://pan.baidu.com/s/1A3chvb8nR3PuOtJPFJHKog

**Comment by yufengwhy** [comment]
谢谢哈。
1. [原数据](https://www.kaggle.com/c/criteo-display-ad-challenge/data)是7天吧？
2. 有没有预处理好的版本，或者预处理code？

**Comment by Atomu2014** [comment]
这是预处理过的7+1天数据（hdf格式），做了降采样，去掉了低频特征。比赛数据随后上传。

**Comment by yufengwhy** [comment]
降采样比例是多少？一般train可以降采样，valid，test不能降采样吧？这个怎么分train，valid，test

**Comment by Atomu2014** [comment]
readme
batch_generator()里面有参数val_ratio，指定训练集中切出多少作为valid

**Comment by yufengwhy** [comment]
我把百度云盘里面的ipinyou下载下来了，用f = h5py.File('ipinyou','r')打开报错OSError: Unable to open file (File signature not found)
@Atomu2014 请问怎么使用

**Comment by Atomu2014** [comment]
下载下来的是分卷压缩文件，首先解压，然后放在datasets/iPinYou.py中 data_dir 指示的位置。
保证 data_dir/hdf 下面是你解压出来的 xxx.h5 文件。
在任何一个可以 import Dataset.py或者iPinYou.py的地方，比如说run.py:

    from iPinYou import iPinYou
    dataset = iPinYou(initialized=True)

    # print meta information about this dataset
    dataset.summary()
    # print feature names
    print dataset.feat_names
    # construct batch generator
    gen = dataset.batch_generator({'gen_type': 'train', 'batch_size': 1000, 'random_sample': True})
    # this loop will iterate this whole dataset once
    for X, y in gen:
        print X.shape, y.shape
        # do something

    # if you want to access this dataset more than once, just reuse `gen`
    for r in num_rounds:
        for X, y in gen:
            # do something

接口由基类Dataset提供，主要访问方式为通过类变量访问数据集的meta info，以及通过batch_generator访问数据。数据访问有on_disk与in_memory两种，两种方式下随机采样的策略有所不同。batch_generator支持的参数有很多，代码里有解释，不懂的话再交流。

**Comment by yufengwhy** [comment]
您好，我解压出来只有一个文件，你是怎么解压的

**Comment by Atomu2014** [comment]
分卷解压
解压出来应该包含100多个 .h5 文件
