### ISSUE TITLE
关于Criteo-8d数据的使用

### ISSUE THREAD

**Issue by gutouyu** [Atomu2014/Ads-RecSys-Datasets#4]
百度网盘中的下载下来后该怎么使用那？PNN论文里也是用这个数据做的实验是吗？非常感谢~

**Comment by Atomu2014** [comment]
下载之后分卷解压得到一系列hdf文件，按照readme中的说明放在指定目录下，使用方法参考样例。这个数据集和readme论文中使用的稍有差别，用这个数据集做的论文目前还不能公开，实验方面可以私下交流

**Comment by gutouyu** [comment]
我再mac上分卷解压失败了。请问下你们用的是啥环境那？关于PNN论文里网络结构已经公式那部分没看太懂，能加个QQ私下聊聊吗？非常感谢~ 马化腾：531267557

**Comment by Atomu2014** [comment]
我是用ubuntu，微信邮件发你了

**Comment by Atomu2014** [comment]
微信：k_innara

ninglee <notifications@github.com> 于2018年6月16日周六 下午3:49写道：

**Comment by gutouyu** [comment]
好的，加你了
