### ISSUE TITLE
about learning procedure

### ISSUE THREAD

**Issue by qk-huang** [Atomu2014/Ads-RecSys-Datasets#5]
Thanks for your sharing these processed datasets. But I have a problem on training model. the DeepFM model get to be convergence very fast. Normally below 5 epoches. In paper PNN, its about at 12 epoch. Do you have same problem? or can you share your training parameters, lr, l2 ?

**Comment by Atomu2014** [comment]
Hi.

Actually, the provided dataset is the second version, which is slightly different from which we used in https://arxiv.org/pdf/1611.00144.pdf. 

Usually, a larger l2 or a smaller lr leads to slower convergence.

We use the second version datasets in this paper https://arxiv.org/pdf/1807.00311.pdf, which is the journal edition of the former PNN paper. In the journal paper, we conduct a lot of experiments and compare 13 models including DeepFM. We find many models converge in less than 5 interactions. You can check the experimental and parameter settings in the journal paper and verify your experiment results.

Hope this will help.

**Comment by qk-huang** [comment]
@Atomu2014 Thanks. You helped me a lot.
