### ISSUE TITLE
may you help download this data CTR Estimation

### ISSUE THREAD

**Issue by Sandy4321** [Atomu2014/Ads-RecSys-Datasets#6]
may you help download this data CTR Estimation
http://apex.sjtu.edu.cn/datasets/18

given link is not working?

**Comment by Atomu2014** [comment]
have you tried this one?
https://pan.baidu.com/s/1usnQtW-YodlPUQ1TNrrafw

**Comment by Sandy4321** [comment]
thanks for link , this does not work neither 
but it asks something strange
![image](https://user-images.githubusercontent.com/11426119/73077886-12825c00-3e8f-11ea-8959-4e4717922c4d.png)

**Comment by Sandy4321** [comment]
The content you downloaded contains folders. Please download it using Baidu Web Client.
Install the latest version of the network disk client

**Comment by Atomu2014** [comment]
Hi, I think you can download each file separately, not the folder.

**Comment by Sandy4321** [comment]
It can not be installed Baidu Web Client.
Can you upload to some less restrictive
For example Dropbox?

**Comment by Atomu2014** [comment]
Hi, I didn't use dropbox before. The basic plan seems to have only 2G storage, which is not enough for even a single criteo dataset. I'll try google cloud at first, and if I finished I will notify you.

**Comment by Sandy4321** [comment]
Sure thanks
You also can find one up to 50gb free
https://www.techradar.com/news/the-best-cloud-storage#best-free-cloud-storage

https://www.mediafire.com/

**Comment by Sandy4321** [comment]
5. MediaFire
A highly experienced cloud storage operator

CHECK AMAZON
Can boost free storage to 50GB
Impressive UI and sharing options
Adverts with free accounts
Free

**Comment by Atomu2014** [comment]
Hi,
try this
https://drive.google.com/drive/folders/1thXezQbmuS6Q8-AXmrhB0tLM3mybJxVR?usp=sharing

**Comment by Sandy4321** [comment]
Great will try
How big data is?

**Comment by Atomu2014** [comment]
around 6G in total

**Comment by Sandy4321** [comment]
great thanks, only can you clarify 
1 
what criteo 8 d means?
2
in which format this data is and what is link to original  the source of this data

**Comment by Sandy4321** [comment]
![image](https://user-images.githubusercontent.com/11426119/73191503-98074580-40f5-11ea-8e12-ba40dcd7c00f.png)

**Comment by Atomu2014** [comment]
criteo 8d means 8 days of criteo logs
I'm not sure where to access the original data, since the old link I know has expired

**Comment by Sandy4321** [comment]
I see thanks for soon answer
Hopefully you can help find some baseline machine learning code to try this data?
