### ISSUE TITLE
do you know code example to run criteo-1tb-benchmark fully locally , without spark? kind of online learning? for  https://labs.criteo.com/2013/12/download-terabyte-click-logs-2/

### ISSUE THREAD

**Issue by Sandy4321** [Atomu2014/Ads-RecSys-Datasets#7]
do you know code example to run criteo-1tb-benchmark fully locally , without spark?
kind of online learning?
for 
https://labs.criteo.com/2013/12/download-terabyte-click-logs-2/

**Comment by Atomu2014** [comment]
have not tried before
