### ISSUE TITLE
can you please share some baseline machine learning code for this data

### ISSUE THREAD

**Issue by Sandy4321** [Atomu2014/Ads-RecSys-Datasets#9]
great job thanks
but now to fully understand potential this project and 
be able to use it
can you please share some baseline machine learning code for this data
so we will be able to learn it by trying

**Comment by Atomu2014** [comment]
I have shared all baselines compared in my papers, see https://github.com/Atomu2014/product-nets and https://github.com/Atomu2014/product-nets-distributed
